site_name: Learnwebsite (Work in Progress)
site_author: Johann Friedrich Heuer
site_description: Documentation for the Informatik AG at the Kaiser-Wilhelm- and Ratsgymnasium Hannover.
site_url: https://kwr-informatik-ag.github.io/learn/en/

# Directories
docs_dir: "../../docs/en"
site_dir: "../../generated/en"

# Repository
repo_name: GitHub Repository
repo_url: https://github.com/kwr-informatik-ag/documentation

# Copyright
# copyright: Copyright &copy; 2024 KWR Hannover

theme:
  name: material
  custom_dir: "../../overrides"
  logo: assets/images/logo-full.png
  favicon: assets/images/favicon.png
  language: en

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    # toc (table of content)
    - toc.follow

    # search
    - search.suggest

    # content
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

    # navigation
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra:
  homepage: https://kwr-informatik-ag.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kwr-informatik-ag/
  analytics:
    provider: google
    property: G-ZMYL9F574V
  alternate:
    # German language
    - name: German
      link: ../de/
      lang: de

    # English language
    - name: English
      link: ../en/
      lang: en

plugins:
  - social
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Homepage: index.md

  - Devops:
      - "Home": devops/index.md
      - Git:
        - "What is git?": devops/git/index.md
        - "Workflows": devops/git/workflows.md
      - Ansible:
        - devops/ansible/index.md
        # - Installation:
        #   - devops/ansible/installation/index.md

  - Languages: # Free-For-All to extend on 
      - "Home": languages/index.md
      - HTML:
        - languages/html/index.md
        - Basics: languages/html/basics.md
      - CSS:
        - languages/css/index.md
      - Javascript:
        - languages/javascript/index.md
        - Typescript:
          - languages/typescript/index.md
      - Python:
        - languages/python/index.md
        - Pipx:
          - languages/python/pipx/index.md
      - YAML:
        - languages/yaml/index.md
    #- C: # Free-For-All to extend on
    #  - languages/javascript/index.md
    #- C#: # Free-For-All to extend on
    #  - languages/javascript/index.md
    #- C++: # Free-For-All to extend on
    #  - languages/javascript/index.md
    #- Java: # Free-For-All to extend on
    #  - languages/java/index.md

  - Frontend:
      - "Home": frontend/index.md
      - NodeJS:
          - Getting Started:
              - "Quick Guide": frontend/nodejs/getting-started/quick-guide.md
              - "Installation": frontend/nodejs/getting-started/installation.md
          - Tutorial:
              - "Basics": frontend/nodejs/tutorial/grundlagen.md
      - Svelte:
          - Getting Started:
              - "Basics": frontend/svelte/getting-started/introduction.md
  - Container:
      - container/index.md
      - Docker:
        - container/docker/index.md

      - Kubernetes:
          - container/kubernetes/index.md

          - Tools:
            - Helm:
                - container/kubernetes/helm/index.md
            - Kustomize:
                - container/kubernetes/kustomize/index.md
            - ArgoCD:
                - container/kubernetes/argocd/index.md
            - Kind:
                - container/kubernetes/kind/index.md


