# Build Stage
FROM python:3.12.1-alpine3.19 AS build
WORKDIR /mkdocs
COPY ./mkdocs .
RUN pip install --upgrade pip && pip install mkdocs-material
RUN mkdocs build

# Web Server Stage
FROM nginx:alpine
COPY --from=build /mkdocs/site/ /usr/share/nginx/html
EXPOSE 80