site_name: Lernwebsite (In Arbeit)
site_author: Johann Friedrich Heuer
site_description: Dokumentation für die Informatik AG am Kaiser-Wilhelm- und Ratsgymnasium Hannover.
site_url: https://kwr-informatik-ag.github.io/learn/de/

# Directories
docs_dir: "../../docs/de"
site_dir: "../../generated/de"

# Repository
repo_name: GitHub Repository
repo_url: https://github.com/kwr-informatik-ag/documentation

# Copyright
# copyright: Copyright &copy; 2024 KWR Hannover

theme:
  name: material
  custom_dir: "../../overrides"
  logo: assets/images/logo-full.png
  favicon: assets/images/favicon.png
  language: de
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  
  features:
    # toc (table of content)
    - toc.follow

    # search
    - search.suggest

    # content
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

    # navigation
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

  palette:
    scheme: slate
    primary: black
    accent: indigo

extra:
  homepage: https://kwr-informatik-ag.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kwr-informatik-ag/
  analytics:
    provider: google
    property: G-ZMYL9F574V

  alternate:
    # German language
    - name: Deutsch
      link: ../de/
      lang: de

    # English language
    - name: Englisch
      link: ../en/
      lang: en

plugins:
  - social
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Startseite: index.md

  - Devops:
      - "Start": devops/index.md
      - Git:
        - "Was ist Git": devops/git/index.md
        - Workflows:
          - "Git Flow": devops/git/workflows/git-flow.md

  - Sprachen:
      - "Start": languages/index.md
      - HTML:
          - languages/html/index.md
          - Grundlagen: languages/html/basics.md
      - CSS:
          - languages/css/index.md
      - Javascript:
          - languages/javascript/index.md
      - Typescript:
          - languages/typescript/index.md
    #- Python: # Free-For-All to extend on
    #  - languages/python/index.md
    #- C: # Free-For-All to extend on
    #  - languages/javascript/index.md
    #- C#: # Free-For-All to extend on
    #  - languages/javascript/index.md
    #- C++: # Free-For-All to extend on
    #  - languages/javascript/index.md
    #- Java: # Free-For-All to extend on
    #  - languages/java/index.md

  - Frontend:
      - "Start": frontend/index.md
      - NodeJS:
          - Erste Schritte:
              - "Schnellanleitung": frontend/nodejs/getting-started/quick-guide.md
              - "Installation": frontend/nodejs/getting-started/installation.md
          - Tutorial:
              - "Grundlagen": frontend/nodejs/tutorial/grundlagen.md
      - Svelte:
          - Erste Schritte:
              - "Grundlagen": frontend/svelte/getting-started/introduction.md
  - Container:
      - container/index.md
      - Docker:
        - container/docker/index.md

      - Kubernetes:
          - container/kubernetes/index.md

          - Tools:
            - Helm:
                - container/kubernetes/helm/index.md
            - Kustomize:
                - container/kubernetes/kustomize/index.md
            - ArgoCD:
                - container/kubernetes/argocd/index.md
            - Kind:
                - container/kubernetes/kind/index.md
